### ISSUE TITLE
Failed to retrieve list of SSH authentication methods: Failed getting response 

### ISSUE THREAD

**Issue by Vitexus** [jbox-web/gitolite-rugged#7]
The problem is maybe in libgit C library compiled wid GEM. Is used rugged/vendor/libgit2 compatible with system
Debian 10 Buster's  /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1  ?

Last hope
```
bundle config --global build.rugged --use-system-libraries
```
Won't help me at all :(

```
2020-06-20 19:14:22 +0200 [INFO] User 'vitex' has created a new repository 'sandbox/testrepo' 
2020-06-20 19:14:23 +0200 [INFO] Create Gitolite Admin directory : '/tmp/redmine_git_hosting/git/gitolite-admin.git' 
2020-06-20 19:14:23 +0200 [DEBUG] Accessing gitolite-admin.git at '/tmp/redmine_git_hosting/git/gitolite-admin.git' 
2020-06-20 19:14:23 +0200 [DEBUG] Settings '{:git_user=>"git", :hostname=>"localhost:22", :host=>"localhost:22", :author_name=>"Redmine Git Hosting", :author_email=>"redmine@vitexsoftware.cz", :public_key=>"/opt/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub", :private_key=>"/opt/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa", :key_subdir=>"redmine_git_hosting", :config_file=>"gitolite.conf", :config_dir=>"conf"}' 
2020-06-20 19:14:24 +0200 [ERROR] Invalid Gitolite Admin SSH Keys 
2020-06-20 19:14:24 +0200 [ERROR] Failed to retrieve list of SSH authentication methods: Failed getting response 
2020-06-20 19:14:24 +0200 [ERROR] ["/usr/lib/ruby/gems/2.5.0/bundler/gems/gitolite-rugged-4f65e51b60ee/lib/gitolite/gitolite_admin/accessors.rb:20:in `clone_at'", "/usr/lib/ruby/gems/2.5.0/bundler/gems/gitolite-rugged-4f65e51b60ee/lib/gitolite/gitolite_admin/accessors.rb:20:in `clone'", "/usr/lib/ruby/gems/2.5.0/bundler/gems/gitolite-rugged-4f65e51b60ee/lib/gitolite/gitolite_admin.rb:180:in `set_repo'", "/usr/lib/ruby/gems/2.5.0/bundler/gems/gitolite-rugged-4f65e51b60ee/lib/gitolite/gitolite_admin.rb:65:in `initialize'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:71:in `new'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:71:in `gitolite_admin'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:45:in `execute_action'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_wrapper.rb:24:in `resync_gitolite'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_accessor.rb:123:in `resync_gitolite'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/gitolite_accessor.rb:36:in `create_repository'", "/opt/redmine/plugins/redmine_git_hosting/app/use_cases/repositories/create.rb:67:in `create_repository'", "/opt/redmine/plugins/redmine_git_hosting/app/use_cases/repositories/create.rb:6:in `call'", "/opt/redmine/plugins/redmine_git_hosting/app/use_cases/repositories/base.rb:21:in `call'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:71:in `call_use_cases'", "/opt/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:33:in `create'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:194:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'", "/opt/redmine/lib/redmine/sudo_mode.rb:65:in `sudo_mode'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:136:in `run_callbacks'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/callbacks.rb:41:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/rescue.rb:22:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/activerecord-5.2.4.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/abstract_controller/base.rb:134:in `process'", "/usr/lib/ruby/gems/2.5.0/gems/actionview-5.2.4.2/lib/action_view/rendering.rb:32:in `process'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:191:in `dispatch'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_controller/metal.rb:252:in `dispatch'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `each'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/journey/router.rb:35:in `serve'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/routing/route_set.rb:840:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:98:in `run_callbacks'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:38:in `call_app'", "/usr/lib/ruby/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `block in call'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'", "/usr/lib/ruby/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/rack/logger.rb:26:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/static.rb:127:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:524:in `call'", "/usr/lib/ruby/gems/2.5.0/gems/passenger-6.0.5/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'", "/usr/lib/ruby/gems/2.5.0/gems/passenger-6.0.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'", "/usr/lib/ruby/gems/2.5.0/gems/passenger-6.0.5/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'", "/usr/lib/ruby/gems/2.5.0/gems/passenger-6.0.5/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'", "/usr/lib/ruby/gems/2.5.0/gems/passenger-6.0.5/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"] 
2020-06-20 19:14:24 +0200 [ERROR] RedmineGitHosting 
```

**Comment by n-rodriguez** [comment]
> Is used rugged/vendor/libgit2 compatible with system
> Debian 10 Buster's /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1

I'm not sure, but there is a 1.0.0 release of rugged that does work with Debian 10 : https://github.com/jbox-web/deploy-it/blob/master/Gemfile#L12.

Maybe we should bump to this release?

**Comment by n-rodriguez** [comment]
Done https://github.com/jbox-web/gitolite-rugged/commit/a0252649b26a190ba5dc97cbb774811389499fa1
